spring.application.name=shareninsulares

spring.datasource.url=jdbc:postgresql://localhost:5432/shareninsulares
spring.datasource.username=postgres
spring.datasource.password=toliveanddie09@

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=shareninsulares-super-secret-key-must-be-at-least-32-chars-long
jwt.expiration=86400000
